### ISSUE TITLE
Error when run example

### ISSUE THREAD

**Issue by takaaptech** [celedev/LuaWatchKitFirstApp#1]
Hi,
I am following the readme but CodeFlow show bellow errors:

12:46:36 AM [CoreLocation.CLLocation, 5] Error: getting field "_structInterface" of a nil object .
12:47:54 AM [CoreLocation.CLLocation, 5] Error: calling a nil function.
12:47:55 AM [MapKit.MKGeometry, 5] Error: getting field "_structInterface" of a nil object .
12:47:57 AM [MapKit.MKGeometry, 5] Error: calling a nil function.
12:47:58 AM [MapKit.MKGeometry, 11] Error: getting field "_structInterface" of a nil object .
12:47:59 AM [MapKit.MKGeometry, 11] Error: calling a nil function.
12:47:59 AM [MapKit.MKGeometry, 18] Error: getting field "_structInterface" of a nil object .
12:47:59 AM [MapKit.MKGeometry, 18] Error: calling a nil function.
12:48:00 AM [MapKit.MKGeometry, 24] Error: getting field "_structInterface" of a nil object .
12:48:00 AM [MapKit.MKGeometry, 24] Error: calling a nil function.
12:48:00 AM [MapKit.MKGeometry, 30] Error: getting field "_structInterface" of a nil object .
12:48:00 AM [MapKit.MKGeometry, 30] Error: calling a nil function.

Can you help me to fix this?

**Comment by jlj** [comment]
@takaaptech, thanks for reporting this issue.
~~After a short investigation, it seems that CodeFlow 0.9.12 is not correctly updating the Xcode target `WatchApp1 WatchKit Extension`.~~
~~I will fix this in the next version.~~

~~In the meantime, you can configure Xcode manually by following these steps:~~
~~1) In Xcode, select the target `WatchApp1 WatchKit Extension`~~
~~2) in this target _build settings_, set `LIBRARY_SEARCH_PATHS` to: `$(USER_LIBRARY_DIR)/Application\ Support/com.celedev.CodeFlow/iphoneos $(USER_LIBRARY_DIR)/Application\ Support/com.celedev.CodeFlow/iphoneos/iOS-8.2-SDK.luabindings/BindingLibs`~~
~~3) in this target _build phases_, open `Link Binary with libraries`, you may see strange _empty_ libraries with no name; remove them and add by drag and drop from the Xcode sidebar the missing bindings libraries: `libCIMLuaBindingFoundation.a`, `libCIMLuaBindingCoreLocation.a`, and `libCIMLuaBindingMapKit.a`.~~
~~4) Compile and run; the errors should be gone.~~
[Edit] Finally the bug was in LuaWatchKitFirstApp (see below).

**Comment by jlj** [comment]
Hi @takaaptech, 
Finally the issue was not in CodeFlow but in LuaWatchKitFirstApp  (i.e. in this repo), where the CodeFlow project  was not set with the correct associated Xcode target `WatchApp1 WatchKit Extension`.

This has been fixed in commit 4e161fe. Please check that these errors are gone.

**Comment by takaaptech** [comment]
I confirm that it works now! Great work!
